---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./actual/ks.yaml
  - ./atuin-server/ks.yaml
  - ./authelia/ks.yaml
  - ./changedetection/ks.yaml
  - ./esphome/ks.yaml
  - ./go2rtc/ks.yaml
  - ./home-assistant/ks.yaml
  - ./homepage/ks.yaml
  - ./mediamtx/ks.yaml
  - ./mosquitto/ks.yaml
  - ./s3-mirror/ks.yaml
  - ./stirling-pdf/ks.yaml
  - ./valetudopng/ks.yaml
  - ./zigbee2mqtt/ks.yaml
