---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: "Europe/Berlin"

  COREDNS_ADDR: "10.43.0.10"
  CLUSTER_CIDR: "10.42.0.0/16"
  SERVICE_CIDR: "10.43.0.0/16"

  NAS_ADDR: "192.168.4.40"
  NAS_ADDR_MINIO_SSD: "192.168.4.40:9000"
  NAS_ADDR_MINIO: "192.168.4.40:9001"

  NODE_CIDR: "192.168.4.0/24"
  KUBE_VIP_ADDR: "192.168.4.250"
  VIP_K8S_GATEWAY: "192.168.4.249"
  VIP_INGRESS: "192.168.4.248"
  VIP_HOME_ASSISTANT: "192.168.4.247"
  VIP_POSTGRES: "192.168.4.246"
  VIP_MOSQUITTO: "192.168.4.245"
  VIP_TASMOADMIN: "192.168.4.244"
  VIP_PLEX: "192.168.4.243"
  VIP_VALETUDOPNG: "192.168.4.242"

  REDIS_DB_AUTHENTIK: "1"
  REDIS_DB_AUTHELIA: "2"
