---
collections:
  - name: ansible.posix
    version: 1.3.0
  - name: community.general
    version: 5.0.2
  - name: kubernetes.core
    version: 2.3.1
  - name: community.sops
    version: 1.2.1
roles:
  - src: xanmanning.k3s
    version: v3.1.2
