---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: external-gateway-proxy
  namespace: networking
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        annotations:
          # external-dns.alpha.kubernetes.io/hostname: "external.${SECRET_DOMAIN}"
          lbipam.cilium.io/ips: "${VIP_EXTERNAL_INGRESS_ENVOY}"
        externalTrafficPolicy: Cluster

---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: internal-gateway-proxy
  namespace: networking
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyDeployment:
        replicas: 2
      envoyService:
        annotations:
          lbipam.cilium.io/ips: "${VIP_INTERNAL_INGRESS_ENVOY}"
        externalTrafficPolicy: Cluster
